CREATE TABLE UF(
    Sigla_UF CHARACTER VARYING(2) NOT NULL,
    Nome_UF CHARACTER VARYING(20) NOT NULL,

    CONSTRAINT PrkUF PRIMARY KEY (Sigla_UF),     
);

CREATE TABLE MUNICIPIO(
    Codigo_Municipio INTEGER NOT NULL,
    Nome_Municipio CHARACTER VARYING(80) NOT NULL,
    Sigla_UF CHARACTER VARYING(2) NOT NULL,
    
    CONSTRAINT PrkMunicipio PRIMARY KEY (Codigo_Municipio),
    CONSTRAINT FrkUfMunicipio FOREIGN KEY (Sigla_UF) REFERENCES UF (Sigla_UF),
);
