# Current learned commands:

- git init
- git remote [add / rm] [origin / name] <URL>
- git diff <HEAD1> <HEAD2>
- git add <path / file>
- git commit [-m "name"] [--amend]
- git log
- git push <remote> <branch / HEAD:branch / tag> [-f]
- git pull [remote / <ULR>] [branch]
- git clone <URL> -b <branch> <directory>
- git checkout [branch] <HEAD> [-- file]
- git revert <HEAD>
- git reset <HEAD> [--hard]
- git branch <name> [-d name]
- git tag <name>
- git merge <URL / remote> <branch>
- git rebase <branch> [-i HEAD]
- git fetch <URL / remote> <branch> <pull/ID/head:BRANCH>
- git stash [pop]
- git blame <file>
- git show <HEAD>
